# <span style="color:darkblue"> Lecture 6d - Website Interaction </span>

<font size = "5">

Import packages for data processing + web scraping

In [2]:
# This command executes the python scripts
exec(open("./scripts/import_packages.py").read())

# <span style="color:darkblue"> I. Initialize Web Driver </span>

In [3]:
# Open browser to start web scraping
options = webdriver.ChromeOptions()
options.headless = False 
driver = webdriver.Chrome(options=options)

# Navigate to specific website
starting_url = 'https://atlas.emory.edu'
driver.get(starting_url)

# <span style="color:darkblue"> II. Interact with forms </span>

<font size = "5">

Emory's Course Atlas website has a searchable form <br>

<font size = "5">


<img src="figures/screenshot_courseatlas_form.png" alt="drawing" width="200"/>

<font size = "5">

Find a form element

<font size = "3">

- Here we search by tag and attribute value
- You can find the "xpath" by going into Developer Tools in Google Chrome

In [ ]:
form_semester = driver.find_element('xpath','//select[@id="crit-srcdb"]')

<font size = "5">

Convert to form

<img src="figures/screenshot_semester_form.png" alt="drawing" width="200"/>

<font size = "3">

- Must convert HTML element suing ```Select()``` function to <br>
enable interactive form capabilities
- Extract the displayed option values with  ```.text``` for each element <br>
or the internal HTML values with 
- We extract the options using a loop

In [5]:
# "Select" is a function from the selenium package
# ".options" extracts the options for Selenium
select_semester = Select(form_semester)
store_options   = select_semester.options
num_options     = len(store_options)

# Store options into a list
list_options = []
for i in range(num_options):
    # This extracts the displayed to 
    option_text = store_options[i].text    
    
    # This extracts the internal HTML values
    # Uncomment this line to display option values instead of displayed text
    # option_text = store_options[i].get_attribute("value")
    list_options.append( option_text )   

list_options

['Fall 2026',
 'Summer 2026',
 'Spring 2026',
 'Fall 2025',
 'Summer 2025',
 'Spring 2025',
 'Fall 2024',
 'Summer 2024',
 'Spring 2024',
 'Fall 2023',
 'Summer 2023',
 'Spring 2023',
 'Fall 2022',
 'Summer 2022',
 'Spring 2022',
 'Fall 2021',
 'Summer 2021',
 'Spring 2021',
 'Fall 2020',
 'Summer 2020',
 'Spring 2020',
 'Fall 2019',
 'Summer 2019',
 'Spring 2019']

<font size = "5">

Select an option

<font size = "3">

- The code displays three equivalent ways of selecting the value <br>
- Once you run this line you should see the Google Chrome browser <br>
interactively select that option, as though you had clicked on it

In [6]:
# Select by visible text
select_semester.select_by_visible_text('Spring 2024')

# select_semester.select_by_index(2)
# select_semester.select_by_value('5241')

<font size = "5">

Type text into a search form

<font size = "3">

- Double check on the browser to see that the information <br>
was entered.

In [7]:
# Find element to enter text
form_search = driver.find_element('xpath','//input[@id = "crit-keyword"]') 

# Clear the text before typing anything
form_search.clear()

# Type something on the screen in the location of that particular element
form_search.send_keys("qtm")

<font size = "5">

Mimic entering "Return" on the keyboard

In [8]:
# "Keys" is a Python object that stands for keyboard
form_search.send_keys(Keys.RETURN)

<font size = "5">

Click on an element

In [9]:
# Find element
form_button = driver.find_element('xpath','//*[@id="search-button"]') 

# Click on element
# Note: Here the element that we choose happens to be a button, but 
# in general you can click on any element, the same way you would do 
# as a user.
form_button.click()

<font size = "5">

Try it yourself!

<font size = "3">

- Find the ``` xpath ``` for the drop-down list "Any Career"
- Select the option "Emory College"
- Send the form

In [6]:
# Write your own code

any_career = driver.find_element('xpath','//*[@id="crit-career"]')
select_career = Select(any_career)
select_career.select_by_visible_text('Emory College')

form_button = driver.find_element('xpath','//*[@id="search-button"]') 
form_button.click()

# <span style="color:darkblue"> III. Interact and Extract Data </span>

<font size = "5">

Some content is only available after interaction

<font size = "3">

- For example, in the course Atlas, some information becomes visible <br>
after you search.
- You need to make sure that the Python code mimics the process <br>
you would use if you were to navigate the website.

<font size = "5">

Enter text in a form

In [7]:
form_search = driver.find_element('xpath','//input[@id = "crit-keyword"]') 
form_search.clear()
form_search.send_keys("computing")
form_search.send_keys(Keys.RETURN)

<font size = "5">

Extract list of resulting options

<font size = "3">

- Find "xpath" by browsing the website in Developer mode

In [9]:
list_results = driver.find_elements('xpath','//div[@class = "result result--group-start"]') 

# Check number of results
num_results = len(list_results)
print(num_results)

41

In [12]:
list_results

[<selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2102")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2103")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2104")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2105")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2106")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2107")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2108")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2109")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2110")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2111")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2112")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2113")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2114")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2115")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2116")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2117")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2118")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2119")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2120")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2121")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2122")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2123")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2124")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2125")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2126")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2127")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2128")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2129")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2130")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2131")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2132")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2133")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2134")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2135")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2136")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2137")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2138")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2139")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2140")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2141")>,
 <selenium.webdriver.remote.webelement.WebElement (session="35b1d3735af14f487f94e165d2cbe74e", element="f.E295474DB7E83D6AA3EDE11F7EA754FB.d.167885EEADB0C17445E85D1E9C0BF258.e.2142")>]

<font size = "5">

Extract information of a particular search result

<font size = "3">

- Conduct search for tags + attributes on subelements
- Use ```.text()``` to extract content
- In this example we are searching for attributes called "result_code" <br>
and "result__title". These names just appear for this Emory website example. <br>
In this example we are also extracting an HTML tag of type "span".

In [10]:
emory_coursecode = list_results[0].find_element('xpath','//span[@class = "result__code"] ').text
emory_classname  = list_results[0].find_element('xpath','//span[@class = "result__title"] ').text

print(emory_coursecode)
print(emory_classname)

CS 110
Computer Science Fundamentals

<font size = "5">

Store extracted data

<font size = "3">

- Conduct search for tags + attributes on subelements
- Use ```.text()``` to extract content
- In this example we are searching for attributes called "result_code" <br>
and "result__title". These names just appear for this Emory website example. <br>
In this example we are also extracting an HTML tag of type "span".

In [ ]:
data = []
for i in range(num_results):
    # Extract data for a specific search results
    # We use parenthesis to split the code into multiple lines to keep
    # things organized.
    emory_coursecode = (list_results[i]
                        .find_element('xpath','.//span[@class = "result__code"] ') # . indicates the relative Xpath within the list
                        .text)
    emory_coursename  = (list_results[i]
                        .find_element('xpath','.//span[@class = "result__title"] ')
                        .text)
    
    # Append data as dictionary
    data.append({"coursecode": emory_coursecode,
                 "coursename": emory_coursename})

# Convert to Pandas DataFrame
data_df = pd.DataFrame(data)

data_df

      coursecode                                         coursename
0         CS 110                      Computer Science Fundamentals
1         CS 170                 Introduction To Computer Science I
2         CS 171                Introduction to Computer Science II
3         CS 190  Fresh Seminar:Computer Science: College in the...
4         CS 224                    Foundations of Computer Science
5         CS 255    Computer Architecture/Machine Level Programming
6         CS 312                     Computing, AI, Ethics, and Soc
7         CS 370                         Computer Science Practicum
8         CS 385    Topics in Computer Science: Learning Assistants
9         CS 442                                    Computer Vision
10        CS 480                     Computing Methods in Economics
11        CS 485   Topics in Computer Science: Human AI Interaction
12        CS 485     Topics in Computer Science: Foundations of HCI
13        CS 485  Topics in Computer Science: Extended Reality S...
14        CS 485  Topics in Computer Science: Intro to Bioinform...
15   DATASCI 150            Introduction to Statistical Computing I
16   DATASCI 151           Introduction to Statistical Computing II
17   DATASCI 185  Applied Topics in Data Science: Computational ...
18   DATASCI 350                             Data Science Computing
19      MATH 170                         Intro.Scientific Computing
20      PHYS 436                     Advanced Computational Physics
21   ARTHIST 210                     Introduction to Graphics & CAD
22        CS 211            Introduction to Artificial Intelligence
23        CS 253                     Data Structures and Algorithms
24        CS 326                             Analysis of Algorithms
25        CS 334                                   Machine Learning
26        CS 456                              Compiler Construction
27       CS 497R                                  Directed Research
28   DATASCI 285  Topics in Data Science: Prediction/InferenceCa...
29   DATASCI 340                      Approaches to Data Sci.w/Text
30   DATASCI 385  Special Topics in Data Science: Quantitative F...
31   DATASCI 385  Special Topics in Data Science: Algorithms in ...
32   DATASCI 385  Special Topics in Data Science: Advanced Netwo...
33   DATASCI 385  Special Topics in Data Science: Policy Debates...
34   DATASCI 385  Special Topics in Data Science: Models of Int'...
35  DATASCI 499R                                  Directed Research
36      ECON 320                                       Econometrics
37      ENVS 365                                    Urban Geography
38       MUS 347                   Electronic Music/Midi Technology
39     PHYS 444W                  Advanced Undergraduate Laboratory
40      SOC 355W                      Research Methods in Sociology

<font size = "5">

Try it yourself!

<font size = "3">

- Expand the dataset above by including the meeting time
- To do so, browse the Emory Course Atlas website in develop mode <br>
and find the tag that is used to denote the course meeting time.
- Try to extract this first for a single element ``` list_results[0] ``` <br>
and once this is working incorporate it into a loop.


Note: In general it's good practice to make sure the code is running <br>
on a single element before automating the process in a loop.

In [ ]:
# Write your own code

emory_classtime  = list_results[0].find_element('xpath', './/span[@class="flex--grow"]').text

print(emory_classtime)

Meets:
MW 1-2:15p

In [23]:
data = []
for i in range(num_results):
    # Extract data for a specific search results
    # We use parenthesis to split the code into multiple lines to keep
    # things organized.
    emory_coursecode = (list_results[i]
                        .find_element('xpath','.//span[@class = "result__code"] ') # . indicates the relative Xpath within the list
                        .text)
    emory_coursename  = (list_results[i]
                        .find_element('xpath','.//span[@class = "result__title"] ')
                        .text)
    time_elements = list_results[i].find_elements(
    'xpath',
    './/span[@class="flex--grow"]')

    emory_coursetime = time_elements[0].text if time_elements else None
    
    # Append data as dictionary
    data.append({"coursecode": emory_coursecode,
                 "coursename": emory_coursename,
                 "coursetime": emory_coursetime})

# Convert to Pandas DataFrame
data_df = pd.DataFrame(data)

data_df

,coursecode,coursename,coursetime
0,CS 110,Computer Science Fundamentals,Meets:\nMW 1-2:15p
1,CS 170,Introduction To Computer Science I,None
2,CS 171,Introduction to Computer Science II,None
3,CS 190,Fresh Seminar:Computer Science: College in the...,Meets:\nTTh 1-2:15p
4,CS 224,Foundations of Computer Science,Meets:\nMW 8:30-9:45a
5,CS 255,Computer Architecture/Machine Level Programming,None
6,CS 312,"Computing, AI, Ethics, and Soc",Meets:\nTTh 8:30-9:45a
7,CS 370,Computer Science Practicum,None
8,CS 385,Topics in Computer Science: Learning Assistants,Meets:\nDoes Not Meet
9,CS 442,Computer Vision,Meets:\nTTh 4-5:15p
10,CS 480,Computing Methods in Economics,Meets:\nMW 2:30-3:45p
11,CS 485,Topics in Computer Science: Human AI Interaction,Meets:\nMW 1-2:15p
12,CS 485,Topics in Computer Science: Foundations of HCI,Meets:\nTTh 5:30-6:45p
13,CS 485,Topics in Computer Science: Extended Reality S...,Meets:\nTTh 2:30-3:45p
14,CS 485,Topics in Computer Science: Intro to Bioinform...,Meets:\nTTh 11:30a-12:45p
15,DATASCI 150,Introduction to Statistical Computing I,Meets:\nMW 4-4:50p
16,DATASCI 151,Introduction to Statistical Computing II,Meets:\nTTh 10-10:50a
17,DATASCI 185,Applied Topics in Data Science: Computational ...,Meets:\nTTh 1-2:15p; F 1-1:50p
18,DATASCI 350,Data Science Computing,Meets:\nTTh 5:30-6:45p
19,MATH 170,Intro.Scientific Computing,None
20,PHYS 436,Advanced Computational Physics,Meets:\nMW 10-11:15a
21,ARTHIST 210,Introduction to Graphics & CAD,Meets:\nT 6-9p
22,CS 211,Introduction to Artificial Intelligence,Meets:\nMW 4-5:15p
23,CS 253,Data Structures and Algorithms,None
24,CS 326,Analysis of Algorithms,None
25,CS 334,Machine Learning,None
26,CS 456,Compiler Construction,Meets:\nTTh 11:30a-12:45p
27,CS 497R,Directed Research,None
28,DATASCI 285,Topics in Data Science: Prediction/InferenceCa...,Meets:\nTTh 4-5:15p; F 2:30-3:20p
29,DATASCI 340,Approaches to Data Sci.w/Text,Meets:\nMW 2:30-3:45p
30,DATASCI 385,Special Topics in Data Science: Quantitative F...,Meets:\nMW 5:30-6:45p
31,DATASCI 385,Special Topics in Data Science: Algorithms in ...,Meets:\nTTh 4-5:15p
32,DATASCI 385,Special Topics in Data Science: Advanced Netwo...,Meets:\nMW 2:30-3:45p
33,DATASCI 385,Special Topics in Data Science: Policy Debates...,Meets:\nTTh 1-2:15p
34,DATASCI 385,Special Topics in Data Science: Models of Int'...,Meets:\nMW 4-5:15p
35,DATASCI 499R,Directed Research,Meets:\nDoes Not Meet
36,ECON 320,Econometrics,None
37,ENVS 365,Urban Geography,Meets:\nMW 10-11:15a
38,MUS 347,Electronic Music/Midi Technology,Meets:\nTTh 1-2:15p
39,PHYS 444W,Advanced Undergraduate Laboratory,Meets:\nMW 1-3:45p
40,SOC 355W,Research Methods in Sociology,Meets:\nTTh 11:30a-12:45p

# <span style="color:darkblue"> IV. Additional Links </span>

<font size = "5">

More information on Selenium:

https://www.selenium.dev/documentation/overview/

Details on clicking through forms:

https://www.selenium.dev/documentation/webdriver/support_features/select_lists/